### ISSUE TITLE
Lib:Elevation needs a libVersion property

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#1]
"Map Elevation Data" has a libVersion property, but when I look at Lib:Elevation, I can't tell what version it is.

**Comment by adventuremagic123** [comment]
"Lib:EventTokens" also needs a libVersion property.  Having this property in all the tokens and libraries helps us know that they are compatible with each other and helps us ensure we're setup right.

**Comment by melek** [comment]
The Map Elevation Data `libVersion` property records the version of the library that created the data token. It is copied directly from Lib:Elevation's `libVersion` property, which is always updated to the current version.

I'm not sure how you are checking the libVersion, but you can always check if the property is defined by typing to following command into chat:

`<pre>[r: json.indent(json.get(getInfo("client"), "library tokens"), 2)]</pre>`

The output will look like this:
```
{
   "Lib:SimpleDoors": "1.0a",
   "Lib:Elevation": "1.0b",
   "Lib:EventTokens": "0.1-b" 
}
```

**Comment by melek** [comment]
For convenience, I've added the version in the GM Name on Lib:Elevation.
