### ISSUE TITLE
I would like to see the link status for a selected token or (if not hard to do) a group of selected tokens.

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#14]
Unless I've missed something, while playing I frequently find a need to find out the status of which elevations my tokens are linked to -- and I don't see a way to do that through the overlay (UI).

I would really like to be able to select a token (one at a time, if needed) and find out which elevations it is linked to.  Even better would be for me to see that for a group of selected tokens.

I don't want my players to see that information, though.  Only GMs.  Even better, only myself.

**Comment by melek** [comment]
Good suggestion. For a single token, this will be very easy to add.

For a group of tokens, how do you imagine the user interface looking for this?

**Comment by melek** [comment]
@adventuremagic123 Once you've helped design the feature I look forward to including it in a future version :)

**Comment by adventuremagic123** [comment]
I'd be okay with a simple text message sent to the GM as a chat message showing the token name and link status for each selected token when clicking a macro button called something like "Link Status".

Something like:

Lib:Elevation token linked status:

Fred the Amazing
[Indented]    Flying (linked)
[Indented]    Ground (not linked)

Brin the Beautiful
[Indented]    Flying (not linked)
[Indented]    Ground (not linked)

Don't need anything complex.

**Comment by melek** [comment]
I've gone with a less featured solution. I'll have to leave it up to the community to mod it further/create a frame to better visualize the unlinked and linked tokens I think, at least for now. 

Instead, you can now see a list of elevations the selected tokens are occupying and/or linked to, though not specified by name. It is not as useful as your suggestion, but was much faster to implement and has already been a convenience. 

Here is what the new display looks like: 
![image](https://user-images.githubusercontent.com/220149/143661523-bc3b979a-de6a-414f-b0ed-542607f9eb59.png)

`Δ - 0` (Delta 0 units between tokens) means the tokens are basically adjacent. 
`ℒ 10` (Linked to elevation 10) part of the readout means that at least some of the selected tokens are linked to that elevation.
`10 - 2 Tokens` means Elevation 10 is occupied by tokens in the selection, and that 2 tokens are selected.
`10 - Upper Floor` is the elevation level and label the map is set to.

It is not perfect, but I hope this is a useful addition in lieu of a new tool. I'll leave open for now until 1.0b8 is officially released.

**Comment by melek** [comment]
Okay I've created a Macro Group / utility to do this, either into chat or on an auto-refreshing frame:
![image](https://user-images.githubusercontent.com/220149/143783902-82b27250-3419-4cc8-8dd3-d64761104c0b.png)

This macro group is attached as follows, **remove the `.zip` extension** and import it to a macro panel using **Import Macro Set...** (GM / Campaign works fine). Both macros need to be in the same location. @adventuremagic123 let me know if this meets your needs and I can include this as a utility macro in 1.0b9:

[showLinkedElevationInfo.mtmacset.zip](https://github.com/melek/lib_elevation/files/7614272/showLinkedElevationInfo.mtmacset.zip)

**Comment by melek** [comment]
This will be included in a future version. Since the utility macros I attached above fill this need immediately for those who want it, I am closing this issue. :)

**Comment by adventuremagic123** [comment]
Sorry for the delay.  I finally tested your macros and they're perfect!  I really like the way you did that -- and provided the choice of dumping the info into the Chat window.  However, I can't tell that's a private message to me.  Might be good to indicate that because GMs would not necessarily want players to see that -- like when they are faced with an invisible NPC.  Adding a header to the message helping me remember it's private would help.  Otherwise, I and other GMs might stop using it if we're not sure whether or not our players can see it. 

Maybe  add something like "As a private message to you:" or something to that effect.  So, example output would look like below (keep in mind that GitHub doesn't show the indents).

As a private message to you:

Shadowy Creature (Shadowy Lurker)
	Ground: Not linked
Sasha Bloodheart (Sasha Bloodheart)
	* Ground: Not linked
Magnus Bloodheart (Magnus Bloodheart)
	* Ground: Not linked
Galirex Hellbane (Galirex Hellbane)
	* Ground: Not linked
Full Plate 2 (Animated Full Plate)
	* Ground: Not linked
Full Plate 1 (Animated Full Plate)
	* Ground: Not linked
Full Plate (Animated Full Plate)
	* Ground: Not linked
Fire Elemental, Large (Fire Elemental, Large)
	* Ground: Not linked
