### ISSUE TITLE
Negative elevations are incorrectly ordered

### ISSUE THREAD

**Issue by alexonyx64** [melek/lib_elevation#17]
I'm not sure if this is actually a bug or if the tool is simply not intended to support negative elevations and I was not aware. I recently tried having multiple levels of elevation with negative values for the first time, and although they did appear below elevation zero the negative elevations themselves were sorted in reverse order, with elevations with greater absolute values being listed as higher.
[Stonegauntlet Landfill Site.rpmap.zip](https://github.com/melek/lib_elevation/files/7695308/Stonegauntlet.Landfill.Site.rpmap.zip)
.

**Comment by melek** [comment]
The tool is supposed to work fine with negative elevations, so thanks for flagging this!

**Comment by melek** [comment]
I found this is due to an issue in MapTool, I've filed a bug here: https://github.com/RPTools/maptool/issues/3878

In the meantime, I've refactored to take advantage of json.sort to get the correct behavior in 1.0rc-1.
