### ISSUE TITLE
Suggested height for new elevations is incorrect

### ISSUE THREAD

**Issue by alexonyx64** [melek/lib_elevation#18]
Since b8, when making new elevations the suggested height does not reflect the height factor set in the map options. Although the ultimate number does seem to be affected by what the height factor is, it is usually in the 100s regardless of what the height factor is or what the height of the current elevation is
[Stonegauntlet Landfill Site.rpmap.zip](https://github.com/melek/lib_elevation/files/7695328/Stonegauntlet.Landfill.Site.rpmap.zip)
.

**Comment by melek** [comment]
This appears to be an incompatibility with 1.12.x. It appears to be an issue with Map Options saving correctly, perhaps also with them reading correctly. 

Thanks!

**Comment by melek** [comment]
I believe this is corrected in 1.0rc-1 with a change to the `setMapOption` macro. The change seems cosmetic, so I did [post in Discord](https://discord.com/channels/296230822262865920/890318378043068456/1087503910392057877) about it in case it surfaces a bug in MapTool.
