### ISSUE TITLE
How do you create PC token at ground level with VBL blocking view of NPC, create fly elevation level, and switch to ...

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#5]
How do you:

1. Create a PC token at ground level.
2. Have VBL block PC's view of an NPC also at ground level.
3. Create a flying elevation level at 60 feet.
4. Switch to fly elevation level while preventing PC token from being selected and revealing the NPC (because this elevation level doesn't have VBL blocking view of the NPC).

Seems like I want the PC and NPC to be faded tokens that are not selectable when I switch to the "Flying" elevation level.

Sorry, but I can't figure out how to get that behavior.  Is there a way?

**Comment by adventuremagic123** [comment]
Discussed with Melek.  There's an option I can't access in Map Options that will disable faded token vision.  Perfect for what I want to do.

**Comment by melek** [comment]
> Discussed with Melek. There's an option I can't access in Map Options that will disable faded token vision. Perfect for what I want to do.

Great! Yes, the "Fog Hack" map option completely restores Fog of War when switching elevation, simulating "floors" between levels. This is a workaround for MapTools lack of getFoW/drawFoW functions.

If you are interested in this feature being improved, please thumbs-up and comment on the MapTool issue: https://github.com/RPTools/maptool/issues/2735
