### ISSUE TITLE
When new elevation level is created with default options, tokens start as opaque.  But, switch to original elevation layer and back to newly created one and tokens are now semi-transparent.

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#6]
When a new elevation layer is created using the default options, the following happens:

1. The new elevation layer is created.
2. The tokens are opaque.  Seems the design is such that they should be semi-transparent.
3. Switch to the previous elevation layer.
4. The tokens are opaque as expected.
5. Switch to the new elevation layer.
6. The tokens are now semi-transparent as expected.

**Comment by adventuremagic123** [comment]
It would also be nice if the semi-transparent tokens either could not be selected or, even better, could not reveal FoW or use their vision.

**Comment by melek** [comment]
You're correct, token states/opacity (I call that 'fading' tokens on different elevations') weren't being updated on adding an elevation. Fixed.

**Comment by melek** [comment]
> It would also be nice if the semi-transparent tokens either could not be selected or, even better, could not reveal FoW or use their vision.

This should be a new issue. However, not being able to select tokens that aren't on the elevation makes it very annoying for players who want to see the map or select tokens when it isn't their turn and they aren't on the current elevation, so I don't think there is a good way to do this. 

I suppose it could be a map option - if you want that, a new issue to track it would be great :)
